
<!-- SLIDER BOF -->
<div class="slider-container clearfix">
<?php if (($_products = $this->getLatestCollection()) && $_products->getSize()): ?>
<div class="latest left">
	<div class="clearfix">
		<h2 class="subtitle"><?php echo $this->__('Latest Arrivals') ?></h2>
		<a href="#" class="jcarousel-prev-horizontal" id="celebrity_latest_prev"></a>
		<a href="#" class="jcarousel-next-horizontal" id="celebrity_latest_next"></a>
	</div>
	<ul id="celebrity_latest" class="jcarousel-skin-tango clearfix">
	<?php foreach ($_products->getItems() as $_product): ?>
	    <li>
		    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
			    <?php echo $this->helper('celebritysettings')->getLabel($_product);  ?>
			    <img data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(112*2, 135*2) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(112, 135) ?>" width="112" height="135" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /><em><?php echo $this->__('Details'); ?></em><span></span>
		    </a>
	    </li>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>

<?php if (($_products = $this->getSaleCollection()) && $_products->getSize()): ?>
<div class="sale right">
	<div class="clearfix">
		<h2 class="subtitle"><?php echo $this->__('On Sale') ?></h2>
		<a href="#" class="jcarousel-prev-horizontal" id="celebrity_sale_prev"></a>
		<a href="#" class="jcarousel-next-horizontal" id="celebrity_sale_next"></a>
	</div>
	<ul id="celebrity_sale" class="jcarousel-skin-tango clearfix">
	<?php foreach ($_products->getItems() as $_product): ?>
	    <li>
		    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
				<?php echo $this->helper('celebritysettings')->getLabel($_product);  ?>
			    <img data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(112*2, 135*2) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(112, 135) ?>" width="112" height="135" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /><em><?php echo $this->__('Details'); ?></em><span></span>
		    </a>
	    </li>
	<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>

</div>
<script type="text/javascript">

jQuery(document).ready(function($) {

	var carouselId = '#celebrity_sale',
		carouselPrev = '#celebrity_sale_prev',
		carouselNext = '#celebrity_sale_next';
	var owl = $(carouselId);

	owl.owlCarousel({

		itemsCustom: [ [0, 3], [480, 4], [768, 2], [1051, 2] ],

		responsiveRefreshRate: 50,
		slideSpeed: 400,
		stopOnHover: true,
		pagination: false,
		itemsScaleUp: false,
		rewindNav: false,

		afterAction: function(){
			if ( this.itemsAmount > this.visibleItems.length ) {
				$(carouselNext).show();
				$(carouselPrev).show();

				$(carouselNext).removeClass('disabled');
				$(carouselPrev).removeClass('disabled');
				if ( this.currentItem == 0 ) {
					$(carouselPrev).addClass('disabled');
				}
				if ( this.currentItem == this.maximumItem ) {
					$(carouselNext).addClass('disabled');
				}

			} else {
				$(carouselNext).hide();
				$(carouselPrev).hide();
			}
		}

	});

	$(carouselNext).click(function(){
		owl.trigger('owl.next');
		return false;
	})
	$(carouselPrev).click(function(){
		owl.trigger('owl.prev');
		return false;
	})

});

jQuery(document).ready(function($) {

	var carouselId = '#celebrity_latest',
		carouselPrev = '#celebrity_latest_prev',
		carouselNext = '#celebrity_latest_next';
	var owl = $(carouselId);

	owl.owlCarousel({

		itemsCustom: [ [0, 3], [480, 4], [768, 4], [1051, 6] ],

		responsiveRefreshRate: 50,
		slideSpeed: 400,
		stopOnHover: true,
		pagination: false,
		itemsScaleUp: false,
		rewindNav: false,

		afterAction: function(){
			if ( this.itemsAmount > this.visibleItems.length ) {
				$(carouselNext).show();
				$(carouselPrev).show();

				$(carouselNext).removeClass('disabled');
				$(carouselPrev).removeClass('disabled');
				if ( this.currentItem == 0 ) {
					$(carouselPrev).addClass('disabled');
				}
				if ( this.currentItem == this.maximumItem ) {
					$(carouselNext).addClass('disabled');
				}

			} else {
				$(carouselNext).hide();
				$(carouselPrev).hide();
			}
		}

	});

	$(carouselNext).click(function(){
		owl.trigger('owl.next');
		return false;
	})
	$(carouselPrev).click(function(){
		owl.trigger('owl.prev');
		return false;
	})

});
</script>
<!-- SLIDER EOF -->
