<?php
$tabs = $this->getTabs();

$custom_tab = Mage::getModel('cms/block')
	->setStoreId( Mage::app()->getStore()->getId() )
	->load('celebrity_custom_tab');
if($custom_tab->getIsActive()) {
	$tabs[] = array(
		'alias' => 'celebrity_custom_tab',
		'title' => $custom_tab->getTitle(),
	);
}

?>
<div class="product-tabs-container clearfix">

	<ul class="product-tabs clearfix">
		<?php foreach ($tabs as $_index => $_tab): ?>
			<?php if($this->getChildHtml($_tab['alias'])): ?>
				<li id="product_tabs_<?php echo $_tab['alias'] ?>" class="<?php echo !$_index?' first':(($_index==count($this->getTabs())-1)?' last':'')?>"><a href="#"><?php echo $_tab['title']?></a></li>
			<?php endif; ?>
		<?php endforeach; ?>
	</ul>
	<?php foreach ($tabs as $_index => $_tab): ?>
		<?php if($this->getChildHtml($_tab['alias'])): ?>
			<h2 id="product_acc_<?php echo $_tab['alias'] ?>" class="tab-heading"><a href="#"><?php echo $_tab['title']?></a></h2>
			<div class="product-tabs-content tabs-content" id="product_tabs_<?php echo $_tab['alias'] ?>_contents"><?php echo $this->getChildHtml($_tab['alias']) ?></div>
		<?php endif; ?>
	<?php endforeach; ?>

</div>

<script type="text/javascript">
	//<![CDATA[
	Varien.Tabs = Class.create();
	Varien.Tabs.prototype = {
		initialize: function(selector) {
			var self=this;
			$$(selector+' a').each(this.initTab.bind(this));
			this.showContent($$(selector+' a')[0]);
		},

		initTab: function(el) {
			el.href = 'javascript:void(0)';
			el.observe('click', this.showContent.bind(this, el));
		},

		showContent: function(a) {
			var li = $(a.parentNode), ul = $(li.parentNode);
			ul.select('li', 'ol').each(function(el){
				var contents = $(el.id+'_contents');
				if (el==li) {
					el.addClassName('active');
					contents.show();
				} else {
					el.removeClassName('active');
					contents.hide();
				}
			});
		}
	}
	new Varien.Tabs('.product-tabs');
	//]]>
</script>