<?php  $_order = $this->getOrder();
$_coreHelper = $this->helper('core'); ?>
<div class="page-title title-buttons">
    <h1><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h1>
</div>
<?php /*
<dl class="order-info">
    <dt><?php echo $this->__('About This Order:') ?></dt>
    <dd>
        <?php $_links = $this->getLinks(); ?>
        <ul id="order-info-tabs">
        <?php foreach ($_links as $_link): ?>
            <?php if($_link->getUrl()): ?>
                <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
            <?php else: ?>
                <li class="current"><?php echo $_link->getLabel() ?></li>
            <?php endif; ?>
        <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateGeneric($('order-info-tabs').select('LI'),['first','last']);</script>
    </dd>
</dl>
*/ ?>
<p class="order-date"><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAt(), 'long')) ?></p>
<?php if (!$_order->getIsVirtual()): ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $this->getShippingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <?php /*
    <div class="col-2">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Shipping Method') ?> ?></h2>
            </div>
            <div class="box-content">
                <?php if ($_order->getShippingDescription()): ?>
                    <?php echo $_order->getShippingDescription() ?>
                <?php else: ?>
                    <p><?php echo $this->helper('sales')->__('No shipping information available'); ?></p>
                <?php endif; ?>
            </div>
        </div>
    </div>
*/ ?>
</div>
<?php endif; ?>
<div class="col2-set order-info-box">
    <div class="col-1">
        <div class="box">
            <div class="box-title">
                <h2><?php echo $this->__('Billing Address') ?></h2>
            </div>
            <div class="box-content">
                <address><?php echo $this->getBillingAddress()->format('html') ?></address>
            </div>
        </div>
    </div>
    <div class="col-2">
        <div class="box box-payment">
            <div class="box-title">
                <h2><?php echo $this->__('Payment Method') ?></h2>
            </div>
            <div class="box-content">
                <?php echo $this->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>

<h2 class="table-caption"><?php echo $this->__('Items Ordered') ?></h2>

<table class="data-table" id="my-orders-table" summary="<?php echo $this->__('Items Ordered') ?>">
    <col />
    <?php /* <col width="1" /> */ ?>
    <col width="1" />
    <col width="40" />
    <col width="40" />
    <col width="1" />
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <?php /* <th><?php echo $this->__('SKU') ?></th> */ ?>
            <th class="a-right"><?php echo $this->__('Price') ?></th>
            <th class="a-center"><?php echo $this->__('Qty Ordered') ?></th>
            <th class="a-center"><?php echo $this->__('Qty Fulfilled') ?></th>
            <th class="a-right"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tfoot>
    <tr class="subtotal">
        <td colspan="4" class="a-right">Subtotal</td>
        <td class="last a-right"><?php echo $_coreHelper->currency($_order->getGrandTotal(), true, false); ?></td>
    </tr>
    <tr class="shipping">
        <td colspan="4" class="a-right">Shipping & Handling</td>
        <td class="last a-right"><?php echo $_coreHelper->currency($_order->getShippingAmount(), true, false); ?></td>
    </tr>
    <tr class="grand_total">
        <td colspan="4" class="a-right"><strong>Grand Total</strong></td>
        <td class="last a-right"><strong><?php echo $_coreHelper->currency($_order->getGrandTotal()+$_order->getShippingAmount(), true, false); ?></strong></td>
    </tr>
    </tfoot>
        <?php $_items = $_order->getItems(); ?>
        <?php $_index = 0; ?>
            <?php $_count = count($_items); ?>
        <?php foreach ($_items as $_item):
                /*$product = Mage::getModel('catalog/product')->load(Mage::getModel('catalog/product')
                        ->getCollection()
                        ->addAttributeToFilter('rex_product_id', $_item['product_id'])
                        ->getFirstItem()->getId());*/ ?>
        <tbody>
            <tr>
                <td><h3 class="product-name"><?php echo $_item['name']; ?></h3></td>
                <?php /* <td><?php echo $product->getSku(); ?></td> */ ?>
                <td><?php echo $_coreHelper->currency($_item['price'], true, false); ?></td>
                <td><b><?php echo $_item['qty']; ?></b></td>
                <td><b><?php echo $_item['qty_fulfilled']; ?></b></td>
                <td><?php echo $_coreHelper->currency($_item['price']*$_item['qty'], true, false); ?></td>
            </tr>
        </tbody>
        <?php endforeach; ?>
</table>